### ISSUE TITLE
Not able to run the exporter as agent

### ISSUE THREAD

**Issue by rksharma1972** [eiiches/scriptable-jmx-exporter#24]
I have attached the error text in file:
[Error_text.txt](https://github.com/eiiches/scriptable-jmx-exporter/files/8336524/Error_text.txt)

I have following jdk version:
eip@fcyeip3297:/home/eip/logs/out-> java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

my test.yaml has following: -
as defined in docs section:
https://github.com/eiiches/scriptable-jmx-exporter#example-exposing-versions-as-info-style-metrics-advanced
[test .yaml.txt](https://github.com/eiiches/scriptable-jmx-exporter/files/8337393/test.yaml.txt)

Thanks,
Rakesh

**Comment by eiiches** [comment]
Hi,

You need to add 

```yaml
rules:
```

right before the `- pattern:` line, like this one: https://github.com/eiiches/scriptable-jmx-exporter#example

Without the `rules:` line, your config accidentally became an array (`[{"pattern": ...}]` in JSON) and that's why you are getting the

```
Cannot deserialize instance of `net.thisptr.jmx.exporter.agent.config.Config$Builder` out of START_ARRAY token
```

error.
